@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

### Auth login
# @name authLogin

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "maria@gmail.com",
    "password":"123456"
}

### Read one user
# @name readOneUser

GET {{baseUrl}}/user/222
Authorization: Bearer {{jwtToken}}

### Create user
# @name createUser

POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria@gmail.com",
    "password":"123456"
}

### Update user
# @name updateUser

PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Matheus",
    "email": "matheus@gmail.com"
}

### Update user password
# @name updateUserPassword

PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPassword": "123456",
    "newPassword": "123456"
}

### Read one user
# @name readUser

GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}


### Delete one user
# @name deleteUser

DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}
