@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

### Auth login
# @name authLogin

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password":"1234"
}

### Read one user
# @name readOneUser

GET {{baseUrl}}/user/222
Authorization: Bearer {{jwtToken}}

### Create user
# @name createUser

POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "User001",
    "email": "user@gmail.com",
    "password":"1234"
}
