@baseUrl = http://localhost:3000

### Auth login
# @name authLogin

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password":"1234"
}

### Read one user
# @name readOneUser

GET {{baseUrl}}/user/222